### PR TITLE
Refactor a bit. Use tuple for encrypt and decrypt functions

### PR DESCRIPTION
**Pull request by vinhnglx**
Hi,

I have refactored a bit of code and then I have implemented encrypt by rsa private key and decrypt by rsa public key.

### CODE REVIEW

**Comment by anoskov** [comment]
Hi @vinhnglx ! Thanks for your PR. I think we need keep `RsaEx.encrypt(clear_text, rsa_public_key)` version for backward compatibility.
So we got two versions:
`def encrypt(message, {:public_key, public_key})`
`def encrypt(message, public_key)`
and same for decrypt.
What you think about this?

**Comment by vinhnglx** [comment]
@anoskov I agree with you. I can update the PR

**Comment by vinhnglx** [comment]
@anoskov I have pushed. Now we have two version, but I added a deprecated attributes for the old version. How do you think?

**Comment by anoskov** [comment]
@vinhnglx Nice! Please squash commits and then i'll merge it.

**Comment by vinhnglx** [comment]
@anoskov done :) .... you can merge .. thank you

**Pull request merged**
