### PR TITLE
Allow custom digest type in sign and verify

### PR DESCRIPTION
**Pull request by hodak**

### CODE REVIEW

**Comment by ArrowsFlying** [comment]
That is the exact thing that I was also planning to request. I was trying to recreate an AWS example of using signed cookies, but it seems they allow only sha1. Don't know why they use that, but at least the user should be allowed to use other digests like SHA-384, SHA-512. Please merge?

**Comment by anoskov** [comment]
@hodak @Vantalk Hi! thanks for pr, but please, add this use case to README and then i merge.

**Comment by hodak** [comment]
@anoskov I believe it's been done separately? https://github.com/anoskov/rsa-ex/commit/d9b5da5fe137e17a599d8bfa3c6085e07f74eea4#diff-04c6e90faac2675aa89e2176d2eec7d8 I think this PR can be closed, then cc @artjimlop

**Comment by anoskov** [comment]
@hodak Yes. Thank you for PR too. U can use ur changes in 0.3. I will close this PR.

**Pull request closed without merging**
